### ISSUE TITLE
Design and create a database schema by writing SQL statements to define tables and relationships

### ISSUE THREAD

**Issue by peposlawa** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-gamers#3]
```[tasklist]
### Tasks
- [x] Generate the database design for the game theme we have chosen using Mermaid Diagram
- [x] Remove existing tables using the 'DROP TABLE' query
- [x] Initiate the 'Platforms' table using the CREATE TABLE query.
- [x] Add columns to the 'Platforms' table for 'platform_id', 'game_title' and 'release_platform' / 'platform_id' being the primary key.
- [x] Initiate the 'Games' table using the CREATE TABLE query.
- [x] Add columns to the 'Games' table for 'game_id', 'game_title', 'release_year', 'genre', 'revenue', 'company_id' and 'platform_id' / 'game_id' being the primary key.
- [x] Initiate the 'Companies' table using the CREATE TABLE query.
- [x] Add columns to the 'Companies' table for 'company_id', 'company_name', 'headquarters' and 'founded_year' / 'company_id' being the primary_key.
- [x] Add values to the 'Platforms' table by using the 'INSERT INTO [column]' query.
- [x] Add values to the 'Games' table by using the 'INSERT INTO [column]' query.
- [x] Add values to the 'Companies' table by using the 'INSERT INTO [column]' query.
```
