### ISSUE TITLE
Implement basic CRUD API routes in Express that query the database and return JSON responses.

### ISSUE THREAD

**Issue by peposlawa** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-gamers#7]
```[tasklist]
### Tasks
- [x] Read - GET endpoints for all three files
- [x] Create - POST endpoints for all three files
- [x] Update - PATCH endpoints for all three files
- [x] Delete - DELETE endpoints for all three files
```

**Comment by peposlawa** [comment]
READ: GET endpoints created for games, companies and platforms. 
All three files updated with getGames, getCompanies & getPlatforms responses for queries. // by @peposlawa

**Comment by peposlawa** [comment]
READ: GET by ID endpoints created for games, companies and platforms.
All three files updated with getGames, getCompanies & getPlatforms responses for queries. // by @Greedent82

**Comment by peposlawa** [comment]
CREATE: POST endpoints created for games, companies and platforms.
All three files updated with getGames, getCompanies & getPlatforms responses for queries. // by @IOLV
