### ISSUE TITLE
Return appropriate HTTP status codes and messages based on API request outcomes.

### ISSUE THREAD

**Issue by peposlawa** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-gamers#8]
```[tasklist]
### Tasks
- [x] Test GET endpoints using Postman.
- [x] Test POST endpoints using Postman.
- [x] Test PATCH endpoints using Postman.
- [x] Test DELETE endpoints using Postman.
```

**Comment by peposlawa** [comment]
All endpoints tested and working.
